version: "3.8"

services:
    db:
        image: postgres:13
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres_laravel
        ports:
            - "5432:5432"
        volumes:
            - db_data:/var/lib/postgresql/data

    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        volumes:
            - .:/var/www/html
        depends_on:
            - db
        environment:
            DB_CONNECTION: pgsql
            DB_HOST: db
            DB_PORT: 5432
            DB_DATABASE: postgres_laravel
            DB_USERNAME: postgres
            DB_PASSWORD: postgres

volumes:
    db_data:
